### ISSUE TITLE
update dwscoalition.org links

### ISSUE THREAD

**Issue by kareila** [dreamwidth/dw-nonfree#102]
Similar to recent dw-free patches filed by @azurelunatic , I notice there are fixes that need to be made in dw-nonfree as well.

In views/misc/about.tt:
- three links to wiki.dwscoalition.org, should be wiki.dreamwidth.net
- one link to bugs.dwscoalition.org, should use https://github.com/dreamwidth/dw-free/issues

In htdocs/stc/syndicateme.css: mark@dwscoalition.org should instead be mark@dreamwidth.org as elsewhere

There's also another Bugzilla link in htdocs/site/suggest.bml but that's linked to the suggestions generator and if poked, a swarm of angry bees may emerge. :bee: :bee: :bee: :bee:

**Comment by srukle** [comment]
@rahaeli in htdocs/site/suggest.bml you create a variable $bugzilla_post on line 131.
> $bugzilla_post .= "http://bugs.dwscoalition.org/enter_bug.cgi?assigned_to=&blocked=&bug_file_loc=http%3A%2F%2F&bug_severity=enhancement&bug_status=NEW&comment=" . $bugzilla_desc . "&contenttypeentry=&contenttypemethod=autodetect&contenttypeselection=text%2Fplain&data=&dependson=&description=&flag_type-1=X&flag_type-10=X&flag_type-11=X&flag_type-2=X&flag_type-3=X&flag_type-5=X&flag_type-7=X&form_name=enter_bug&keywords=from-suggestions&op_sys=All&priority=P-&product=Dreamwidth%20Development&qa_contact=&rep_platform=All&short_desc=" . $bugzilla_subject . "&target_milestone=-undecided-&version=1.0";

Because http://bugs.dwscoalition.org/ no longer seems to respond to pings, I assume it's gone. What do you imagine putting here instead? Is there a new location you'd like the end-user to submit tickets -- or does everything go through GitHub?

**Comment by rahaeli** [comment]
That's a bit of a complicated situation. Basically: htdocs/site/suggest.bml is the page at https://www.dreamwidth.org/site/suggest for people to submit suggestions. Once submitted, they're put in the moderation queue for https://dw-suggestions.dreamwidth.org/. The bits of code around that line also create a second (private) post, posted to the community, that would let me repost the suggestion to Bugzilla with one click, for easy transfer of suggestions into bug tracking.

When we converted from Bugzilla to Github Issues, that feature (obviously) broke -- the private/admin-only posts are still generated, but they don't work to open a ticket anymore. I did a cursory investigation when we switched and didn't find any real way to accomplish the same thing with Github Issues, but I didn't want to disable the private/admin-only posts entirely because I use them as a) a cross-check that I haven't lost any suggestions and b) to keep the text of the suggestion if it gets deleted.

Let's say that you can just leave it alone for now, and I'll open another issue to switch that bit of code over to just post an entry with the text of the suggestion instead.

**Comment by me-and** [comment]
Claim
