### ISSUE TITLE
change suggestions generator to post copy of suggestion, not bugzilla link

### ISSUE THREAD

**Issue by rahaeli** [dreamwidth/dw-nonfree#106]
See issue #102 for discussion and background here: the suggestions generator (/htdocs/site/suggest.bml) generates a post-to-Bugzilla link, posted admin-only in the comm, for every suggestion. Bugzilla doesn't work anymore, so neither do those links, but having the backup copy of the suggestion is very useful for both a cross-check that I haven't lost suggestions and as a backup in case the original suggestion gets deleted.

So, lines 107-160 should be changed to:

* still post as $suggestions_bot, and still post privately;
* but instead, replicate the user-facing post built in lins 70-103;
* with the addition of "Suggested by: (suggester's username)";
* without the poll (it's not necessary);
* and putting the entire post behind a cut.

A link to https://github.com/dreamwidth/dw-free/issues/new -- even if none of the fields can be autopopulated -- would be pretty helpful, too.

**Comment by me-and** [comment]
I just spotted this. My PR #108 more-or-less covers all this, but I was working from dreamwidth/dw-free#662, which provides a link like the old Bugzilla link to a pre-populated new GHI page. Does that give you everything you need here? It has the full text of the suggestion, just encoded in the link to open a new GHI rather than readily visible behind a cut.

**Comment by me-and** [comment]
Claim.

**Comment by rahaeli** [comment]
I had actually completely forgotten I'd opened that other issue when I opened this one -- I had it in my head that we'd decided it wouldn't be possible to do a GHI auto(ish)-post at all! So, please ignore this issue, it was operator error.
